<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('st_templates')
            ->where('configuration->nomor_surat_format', 'like', 'ST.%')
            ->get(['id', 'configuration'])
            ->each(function (object $template): void {
                $configuration = json_decode($template->configuration ?: '{}', true) ?: [];
                $format = (string) ($configuration['nomor_surat_format'] ?? '');
                $configuration['nomor_surat_format'] = preg_replace('/^ST\.\{nomor\}/', '', $format) ?: '/K.18/TU/{klasifikasi}/B/{bulan}/{tahun}';

                DB::table('st_templates')
                    ->where('id', $template->id)
                    ->update(['configuration' => json_encode($configuration)]);
            });
    }

    public function down(): void
    {
        // Keep normalized formats on rollback; the prefix is now generated by the application.
    }
};
