<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Core\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        // First truncate to avoid duplicates if re-running without fresh db
        Employee::truncate();

        $employees = [
            [
                'nip' => '197405141999031001',
                'name' => 'Matheas Ari Wibawanto, S.Hut., M.Sc.',
                'position' => 'Kepala Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'rank' => 'Pembina Tingkat I (IV/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197312101999031002',
                'name' => 'Dr. Suryadi, S.H., M.Si.',
                'position' => 'Polisi Kehutanan Ahli Madya',
                'rank' => 'Pembina Tingkat I (IV/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197308202000032003',
                'name' => 'Ulfa Rosyida, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Madya',
                'rank' => 'Pembina Tingkat I (IV/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197511272000032001',
                'name' => 'Suriawati Halim, S.Hut., M.P.',
                'position' => 'Kepala Seksi Konservasi Sumber Daya Alam Wilayah II',
                'rank' => 'Pembina (IV/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197406262001121004',
                'name' => 'Bambang Hari Trimarsito, S.Si., M.P.',
                'position' => 'Kepala Seksi Konservasi Sumber Daya Alam Wilayah III',
                'rank' => 'Pembina (IV/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198007072006041003',
                'name' => 'Yulian Sadono, S.Hut., M.T.',
                'position' => 'Kepala Seksi Konservasi Sumber Daya Alam Wilayah I',
                'rank' => 'Pembina (IV/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197307141998032003',
                'name' => 'Ratna Juliarti Wulandari, S.Hut., M.T.',
                'position' => 'Penelaah Teknis Kebijakan',
                'rank' => 'Pembina (IV/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197012282002121001',
                'name' => 'drh. Amir Ma\'ruf, M. Hum.',
                'position' => 'Penelaah Teknis Kebijakan',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198206262008022001',
                'name' => 'Maria Anna Raheni, S.Sos.',
                'position' => 'Pustakawan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197503111999031004',
                'name' => 'Dheny Mardiono, S.Hut., M.Sc.',
                'position' => 'Kepala Sub Bagian Tata Usaha',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198409242008012008',
                'name' => 'Dhani Silvia Wati, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198701302010122005',
                'name' => 'Dilemma Ferti Hidayah, S.E.',
                'position' => 'Analis Pengelolaan Keuangan APBN Ahli Pertama',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198107142000121002',
                'name' => 'Prajoko, S.Hut.',
                'position' => 'Pengelola Pengadaan Barang/Jasa Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198305282001121001',
                'name' => 'Heryanto Sumanbowo, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198310072001122001',
                'name' => 'Posda Gressya Sitompul, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198112232000121002',
                'name' => 'Ahmad Nuryani, S.PKP.,M.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197907212007012001',
                'name' => 'Soerendeng, S.E',
                'position' => 'Penelaah Teknis Kebijakan',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198411172003121006',
                'name' => 'Arsyat Hatta, S.Hut',
                'position' => 'Polisi Kehutanan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197808212000032002',
                'name' => 'Errin Agustina, A.Md.',
                'position' => 'Pengendali Ekosistem Hutan Penyelia',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198104252001121002',
                'name' => 'Sumarso, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198108242000121002',
                'name' => 'Agung Suseno, S.PKP.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198206122000121003',
                'name' => 'Mohamad Fahruroji, S.P.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198303132001121002',
                'name' => 'Yoyok Sugianto, S.Hut., M.Ling.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197501301997031001',
                'name' => 'Nidiansjah',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197212141999031003',
                'name' => 'Wilyanto, A.Md.',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata Tingkat I (III/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198106052000121004',
                'name' => 'Rido, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197411102005011012',
                'name' => 'Novrianus Edwin Kinbenu, S.P.',
                'position' => 'Polisi Kehutanan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197505052007101001',
                'name' => 'Hendra Jaya, S.H.',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198501312007101001',
                'name' => 'Muhammad Irsyad, S.H.',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198204252009012008',
                'name' => 'Siti Nurul Arshinta Dewi, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197205022007101001',
                'name' => 'Fransiskus Sega',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197510241999031004',
                'name' => 'Muhadi',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198109162008012001',
                'name' => 'Fitriany M., S.Hut.,M.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198201282000121001',
                'name' => 'Bahari Tao Hutabarat, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198607282009122003',
                'name' => 'Iin Anggraini, S.Si.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198203012000121001',
                'name' => 'Ahmad Hidayat, S.PKP., M.Ling.',
                'position' => 'Pengelola Pengadaan Barang/Jasa Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198206042000121003',
                'name' => 'Puji Mulyanto, S.Hut.,M.P.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197912232000121001',
                'name' => 'Witono, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198210272000121002',
                'name' => 'Jono Adi Putro, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198506022009122001',
                'name' => 'Hajar Intan Ramadhania, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197408221998031002',
                'name' => 'Tri Agus Cahyono',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198411072003122003',
                'name' => 'Ismi Hartuti',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198004122000121003',
                'name' => 'Ahmad Ripai, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Muda',
                'rank' => 'Penata (III/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197202011997031006',
                'name' => 'Hardi Purnama',
                'position' => 'Pengolah Data dan Informasi',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197504282007101001',
                'name' => 'Syaifurrakhman',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198109072000121004',
                'name' => 'Rusmanto, S.Hut.',
                'position' => 'Pengelola Pengadaan Barang/Jasa Ahli Pertama',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198405092007101001',
                'name' => 'Rudy Handoko',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197208292007101001',
                'name' => 'Agustaf Samber',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198112152005012014',
                'name' => 'Menik Tjahyoningrum, A.Md.',
                'position' => 'Pengendali Ekosistem Hutan Penyelia',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198002162000121001',
                'name' => 'Muhammad Saleh',
                'position' => 'Pengendali Ekosistem Hutan Penyelia',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198507072003122003',
                'name' => 'Santi Rerok, S.H.',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '198201032000121002',
                'name' => 'Nuriadi Yudistira, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198408162006041004',
                'name' => 'Hasrul Nordiansyah, S.Hut.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198001092000121003',
                'name' => 'Rusmin Nuryadin',
                'position' => 'Pengendali Ekosistem Hutan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197704171997031002',
                'name' => 'Amos Robi Simon',
                'position' => 'Pengendali Ekosistem Hutan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197910151999031003',
                'name' => 'I Ketut Sukana',
                'position' => 'Pengendali Ekosistem Hutan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197504192007101002',
                'name' => 'Dwi Suriyanto',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198512272020121005',
                'name' => 'Herdi Yusuf, S.Hut.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199101102015022003',
                'name' => 'Frika Purnamasari, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda Tingkat I (III/b)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198501082015021001',
                'name' => 'Yan Bastian Gultom, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198807192020121003',
                'name' => 'Didi Susanto, S.Si.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198401092006041003',
                'name' => 'Zainul Robiansyah',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197509192006041011',
                'name' => 'Didimus',
                'position' => 'Pengolah Data dan Informasi',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198510162007101001',
                'name' => 'Prawira Harja, S.P.',
                'position' => 'Pengendali Ekosistem Hutan Mahir',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197604141999031003',
                'name' => 'Surya Darmawan, A.Md.',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199111272025061004',
                'name' => 'Herman Wisnanda Lubis, S.P.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '199308162025061005',
                'name' => 'Afrizal Maula Alfarisi, S.Hut.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199410152025061006',
                'name' => 'Ahmad Mukhdlor, S.Hut.',
                'position' => 'Polisi Kehutanan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199906242025061006',
                'name' => 'Junian Adi Cahya, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199901012025061008',
                'name' => 'Jatu Kusuma Rahardian, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200108042025061008',
                'name' => 'Jeamshen Christian Simon, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '200207312025062007',
                'name' => 'Carica Deffa Yullinda, S.Kom.',
                'position' => 'Pranata Komputer Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199911032025062012',
                'name' => 'Anisa Rahmawati, S.Tr.Kom.',
                'position' => 'Pranata Komputer Ahli Pertama',
                'rank' => 'Penata Muda (III/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198007132000031002',
                'name' => 'Djunaib Ahmad',
                'position' => 'Pengendali Ekosistem Hutan Mahir',
                'rank' => 'Pengatur Tingkat I (II/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197907172000121002',
                'name' => 'Aripin',
                'position' => 'Pengendali Ekosistem Hutan Terampil',
                'rank' => 'Pengatur Tingkat I (II/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198406182007101001',
                'name' => 'Ashar Ramadhona',
                'position' => 'Polisi Kehutanan Penyelia',
                'rank' => 'Pengatur Tingkat I (II/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198406252005011005',
                'name' => 'Syahidul Anwar',
                'position' => 'Polisi Kehutanan Mahir',
                'rank' => 'Pengatur Tingkat I (II/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '197708081998031004',
                'name' => 'Khairul Falah',
                'position' => 'Pengolah Data dan Informasi',
                'rank' => 'Pengatur Tingkat I (II/d)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197405142000031001',
                'name' => 'Untung Raharjo, A.Md.',
                'position' => 'Pengendali Ekosistem Hutan Terampil',
                'rank' => 'Pengatur (II/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199703312022032014',
                'name' => 'Putri Pratiwi, A.Md.',
                'position' => 'Pengendali Ekosistem Hutan Terampil',
                'rank' => 'Pengatur (II/c)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199504082015022001',
                'name' => 'Rara Nieng Zulaikhah',
                'position' => 'Polisi Kehutanan Terampil',
                'rank' => 'Pengatur (II/c)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199907072025061006',
                'name' => 'Tegar Anugrah, A.Md.Kom.',
                'position' => 'Pranata Komputer Terampil',
                'rank' => 'Pengatur (II/c)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199908082019022001',
                'name' => 'Nur Laili Choirul Ummah',
                'position' => 'Polisi Kehutanan Terampil',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199907082022032007',
                'name' => 'Putri Nanda Wulansari',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '199605052022031005',
                'name' => 'Guntur Adjie Dimas Karebet',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199306242025061001',
                'name' => 'Affi Agung Rahmadi',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199808112025061006',
                'name' => 'Bagus Linggo Saputra',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199810042025061009',
                'name' => 'Ari Harianto',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '200005202025061009',
                'name' => 'Julian Airlangga Syah',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200106112025061012',
                'name' => 'Resqie Younior Wibowoputra',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '200108302025061006',
                'name' => 'James Fiqihsantana Catur Almuminun',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200204112025062005',
                'name' => 'Badriah Nur Khalizah',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '200306092025061001',
                'name' => 'Asriadi',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200409092025061001',
                'name' => 'Naufal Hafizh Taufiqul Hakim',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '200503162025062003',
                'name' => 'Mita Kanisaputri',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '200506182025061003',
                'name' => 'Dimas Kendha Fitrianto',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200512242025061001',
                'name' => 'Dhean Wiguna Prayitno',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => 'Pengatur Muda (II/a)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199703162023212021',
                'name' => 'Giga Piancita, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '199607222023211007',
                'name' => 'Anas Jaya Kurniawan, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199306132023212057',
                'name' => 'Wa Ode Fikih Hairunisa, S.E.',
                'position' => 'Perencana Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199304252024212053',
                'name' => 'Sukma Mawarni, S.E.',
                'position' => 'Perencana Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199212192024211021',
                'name' => 'Boyekasujarwo, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '199601032024212050',
                'name' => 'A. Aliah Indah Fitriah, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199711012024212054',
                'name' => 'Eni Susanti, S.Hut.',
                'position' => 'Pengendali Ekosistem Hutan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '199511282024212031',
                'name' => 'Nurviona Shahira, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199612182024212035',
                'name' => 'Dian Anggraini, S.E.',
                'position' => 'Analis Sumber Daya Manusia Aparatur Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '198909142024211031',
                'name' => 'Muh Arsal, S.Hut.',
                'position' => 'Penyuluh Kehutanan Ahli Pertama',
                'rank' => '(IX)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '199612222023211005',
                'name' => 'Yogi Pratama',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '199702182023212019',
                'name' => 'Mega Wahyu Birinda',
                'position' => 'Polisi Kehutanan Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '200009222024211004',
                'name' => 'Achmad Syafey N',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '200305132024211001',
                'name' => 'Friederich J.h',
                'position' => 'Pengendali Ekosistem Hutan Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
            [
                'nip' => '198906062025211132',
                'name' => 'Wahyuddin',
                'position' => 'Manggala Agni Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '196906172025211013',
                'name' => 'Abdurrahman',
                'position' => 'Manggala Agni Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '197312122025211047',
                'name' => 'Suryadi',
                'position' => 'Manggala Agni Pemula',
                'rank' => '(V)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '199310222025211076',
                'name' => 'Yonatan',
                'position' => 'Manggala Agni Pemula',
                'rank' => '(V)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah II',
                'is_active' => true,
            ],
            [
                'nip' => '198404282025211065',
                'name' => 'Taufik Rahman',
                'position' => 'Manggala Agni Pemula',
                'rank' => '(V)',
                'department' => 'Kantor Balai Konservasi Sumber Daya Alam Kalimantan Timur',
                'is_active' => true,
            ],
            [
                'nip' => '197602182025211022',
                'name' => 'Rismanto',
                'position' => 'Pengelola Umum Operasional',
                'rank' => '(III)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah I',
                'is_active' => true,
            ],
            [
                'nip' => '197107202025212013',
                'name' => 'Asrina',
                'position' => 'Pengelola Umum Operasional',
                'rank' => '(I)',
                'department' => 'Seksi Konservasi Sumber Daya Alam Wilayah III',
                'is_active' => true,
            ],
        ];

        foreach ($employees as $emp) {
            Employee::create($emp);
        }
    }
}
